spring:
   data:
      mongodb:
         uri: mongodb+srv://chat_user:uk0IAPnAKhc7wLwk@cluster0.tnbctsc.mongodb.net/chat-application?retryWrites=true&w=majority
   servlet:
      multipart:
         max-file-size: 10KB
         max-request-size: 5MB

baseUrl: https://howzz-frontend.herokuapp.com
   
